repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.9.17
  hooks:
  - id: uv-lock
  - id: uv-export
- repo: https://github.com/psf/black
  rev: 25.12.0
  hooks:
  - id: black
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.8
  hooks:
  - id: ruff-check
  - id: ruff-format
